version: "3.8"

services:
  mongodb:
    image: "mongo"
    container_name: database
    volumes:
      - mongodb_data:/data/db
      - ./db-script/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
      - ./db-script/seed-boardgame.js:/docker-entrypoint-initdb.d/seed-boardgame.js:ro
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - .env


  backend:
    image: node:latest
    working_dir: /app/be
    build:
      context: ./bge-be/
      dockerfile: Dockerfile
    volumes:
      - ./bge-be:/app/be
      - /app/be/node_modules
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_URL: "mongodb://database:27017"
    depends_on:
      - mongodb
    command: pnpm start:docker

  frontend:
    image: node:latest
    working_dir: /app/fe
    build:
      context: ./bge-fe/
      dockerfile: Dockerfile
    volumes:
      - ./bge-fe:/app/fe
      - /app/fe/node_modules
    ports:
      - "3000:3000"
    command: "pnpm dev"

volumes:
  mongodb_data:
