import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const Navbar = dynamic(() => import("@/components/NavBar/NavBar"), {
        ssr: false,
    });

    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <Providers>
                    <div className="sticky inset-0 bg-[--page-background] z-40">
                        <Navbar />
                    </div>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
